name: Scheduled Python Scripts

on:
  schedule:
    - cron: "2 20 * * *"  # Runs daily at 19:02 UTC (3:02 AM CST)
    - cron: "7 16 * * 4"  # Runs weekly at 16:05 UTC (Friday 00:05 CST)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_daily_script:
    if: github.event.schedule == '2 20 * * *'  # Only runs for the daily schedule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Ensures full history is pulled to prevent conflicts

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests pandas  # Add any other dependencies

      - name: Run bobao.py (Daily)
        run: python bobao.py

      - name: Run bidu.py (Daily)
        run: python bidu.py

      - name: Pull latest changes to avoid conflicts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/GingerCP/gongzicpdata.github.io.git
          git pull --rebase origin main || echo "No changes to pull"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add bobao.json bidu.json
          git commit -m "Daily update from bobao.py & bidu.py" || echo "No changes to commit"
          git push origin main || (git pull --rebase origin main && git push origin main)

  run_weekly_script:
    if: github.event.schedule == '7 16 * * 4'  # Only runs for the weekly schedule
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0  # Ensures full history is pulled to prevent conflicts

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests pandas  # Add any other dependencies

      - name: Run scrape_and_update.py (Weekly)
        run: python scrape_and_update.py

      - name: Run qiangtui.py (Weekly)
        run: python qiangtui.py

      - name: Run renqijiazuo.py (Weekly)
        run: python renqijiazuo.py

      - name: Run chunaitaojin.py (Weekly)
        run: python chunaitaojin.py

      - name: Pull latest changes to avoid conflicts
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/GingerCP/gongzicpdata.github.io.git
          git pull --rebase origin main || echo "No changes to pull"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git add output_data.json
          git add benzhouqiangtui.json
          git add renqijiazuo.json
          git add chunaitaojin.json
          git commit -m "Weekly update from scrape_and_update.py" || echo "No changes to commit"
          git push origin main || (git pull --rebase origin main && git push origin main)
