name: Scheduled Python Scripts

on:
  schedule:
    - cron: "5 16 * * *"  # Runs script.py every day at 00:05 Beijing Time (UTC 16:05)
    - cron: "5 16 * * 5"  # Runs script2.py every Friday at 00:05 Beijing Time (UTC 16:05)
  workflow_dispatch:  # Allows manual trigger

jobs:
  run_daily_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests pandas  # Add any other dependencies

      - name: Run bobao.py (Daily)
        run: python bobao.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/YOUR_USERNAME/YOUR_REPO.git
          git add bobao.json  # Modify this if your script updates a different file
          git commit -m "Daily update from bobao.py" || echo "No changes to commit"
          git push origin main

  run_weekly_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: pip install requests pandas  # Add any other dependencies

      - name: Run scrape_and_update.py (Weekly)
        run: python scrape_and_update.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/YOUR_USERNAME/YOUR_REPO.git
          git add output_data.json  # Modify this if script2 updates a different file
          git commit -m "Weekly update from crape_and_update.py" || echo "No changes to commit"
          git push origin main
